spring.application.name=API-GATEWAY

server.port=8087

spring.cloud.gateway.routes[0].id=COMPANY-PRODUCT
spring.cloud.gateway.routes[0].uri=lb://COMPANY-PRODUCT
spring.cloud.gateway.predicates[0]=path=/company/**,/test/**


spring.cloud.gateway.routes[1].id=PRODUCT
spring.cloud.gateway.routes[1].uri=lb://PRODUCT-PRODUCT
spring.cloud.gateway.predicates[1]=path=/product/**

